---
title: "country_urbanization"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load libraries

library(tidyverse)
library(here)
library(viridis)
library(sf)
library(tmap)
library(ggpp)
library(raster)
library(rasterVis)
library(readxl)
library(xml2)
library("RColorBrewer")
library(foreign)
library(haven)
library(Hmisc)
library(fuzzyjoin)
```


```{r}
## Read kenya population density data

path <- "G://Shared drives//DATA_WDL//Mpro_2.0//01_Data//R_2022_12_29//2023_01_23_2017ppp//01_inputs//population//World pop//Kenya"

ken <-  raster(paste0(path, "\\ken_pd_2020_1km_UNadj.tif"))

##Read Kenya consumption survey data

ken_cons <- read_dta("ken_consumption//Consumption_aggregate.dta")

#Read conversion factors

ppp_2017 <- read_rds("01_010_conversion_factors.rds")

## Read shape file


shape_kenya <- read_sf(here::here("ken_shape/gadm41_KEN_1.shp"))


```

## Aggregate consumption kenya

```{r}
unique(ken_cons$county)
```


```{r}

#Convert column county and resid to factor columns
ken_cons$county <- as_factor(ken_cons$county)
ken_cons$resid <- as_factor(ken_cons$resid)
ken_cons$eatype <- as_factor(ken_cons$eatype)
```



```{r}
#Get the total consumption

ken_cons <- ken_cons %>%
    mutate(tot_cons = rowSums(dplyr::select(., padqnfitems:padqfdcons)))


```

```{r}
#Covert local currency into 2017 ppp and create spending groups

ppp_2017_ken <- ppp_2017 %>% 
    filter(ccode == "KEN")


ken_cons <- ken_cons %>% 
    mutate(tot_cons_ppp = (tot_cons*0.37776351))

```


```{r}


# Select relevant variables from survey data

ken_var <- ken_cons %>% 
    dplyr::select(county, resid,weight_pop,tot_cons)

# Compute quantiles

ken_qnt <- wtd.quantile(ken_var$tot_cons, weights = ken_var$weight_pop, probs = seq(0, 1, 0.1))

# create data frame with quantiles and corresponding cons values
ken_qnt <- data.frame(cbind(names(ken_qnt), ken_qnt))
names(ken_qnt) <- c("quantile", "value")
ken_qnt$value <- as.numeric(ken_qnt$value)



# match data with quantiles
ken_var$quantile <- ken_qnt$quantile[findInterval(ken_var$tot_cons, ken_qnt$value, all.inside = TRUE)+1]

ken_var %>% 
    View()
```


```{r}
# compute shares of groups per quantile
ken_var2 <- ken_var %>%
  group_by(resid) %>%
  mutate(wgt_qtl = sum(weight_pop)) %>% 
  group_by(quantile, resid) %>%
  summarise(share = sum(weight_pop)/wgt_qtl) %>%
  distinct()


ken_var2 %>% 
    pivot_wider(names_from = resid, values_from = share) %>% 
    write_csv("quantiles1.csv")

```
```{r}

# calculate the weighted mean spending for each county
county_wtd_mean <- ken_var %>%
  group_by(county) %>%
  summarise(avg_spend_per_person = wtd.mean(tot_cons, weights = weight_pop))


# calculate the average spend per person for all rural and all urban

resid_wtd_mean <- ken_var %>%
  group_by(resid) %>%
  summarise(avg_spend = wtd.mean(tot_cons, weights = weight_pop))

```
```{r}
# Multiply county urbanization rates by average spend per person in each rural and urban area

county_avg_spending <- shape_kenya %>%
   mutate(avg_spend = (urbanization2/100 * 18450.799) + (rural/100 * 9094.087)) %>% 
   rename(county = NAME_1)

```




```{r}

# clean up the county names by removing non-alphanumeric characters
county_avg_spending$county <- gsub("[^[:alnum:]]", "", county_avg_spending$county)
county_wtd_mean$county <- gsub("[^[:alnum:]]", "", county_wtd_mean$county)

#Merge the two data frames for plotting

# Join by county names

shape_kenya2 <- regex_left_join(county_avg_spending , county_wtd_mean, by = "county", ignore_case = TRUE)

```


## World bank urbanization classification
```{r}
# Extract population values

library(exactextractr)

shape_kenya$pop_2020 <- exact_extract(ken, shape_kenya, "sum")

```



```{r}
# Convert county area to square kilometers
shape_kenya$area_km2 <- st_area(shape_kenya) / 1e+06
```


```{r}
# Calculate population density for each county in square kilometers
shape_kenya$pop_density_km2 <- shape_kenya$pop_2020 / shape_kenya$area_km2
```

```{r}
# Remove [1/m^2] from pop_density_km2
shape_kenya$pop_density_km2 <- gsub("\\s*\\[1/m\\^2\\]", "", shape_kenya$pop_density_km2)
shape_kenya$pop_density_km2 <- as.numeric(shape_kenya$pop_density_km2)
```




```{r}
# Create new column for city/town/rural classification
#shape_kenya$urbanization <- ifelse(shape_kenya$pop_2020 > 50000 & shape_kenya$pop_density_km2 > 1500, "City", 
                                      #ifelse(shape_kenya$pop_2020 > 5000 & #shape_kenya$pop_density_km2 > 250, "Town", "Rural"))

```



```{r}

#calculate the urbanization rate for each county

shape_kenya$urbanization <- ifelse(shape_kenya$pop_density_km2 > 1500 & shape_kenya$pop_2020 >= 50000,(0.6 * (shape_kenya$pop_density_km2 / max_density) + 0.4 * (shape_kenya$pop_2020 / max_pop)) * 100,
                            ifelse(shape_kenya$pop_density_km2 > 250 & shape_kenya$pop_2020 >= 5000,
                                            (0.2 * (shape_kenya$pop_density_km2 / max_density) + 0.8 * (shape_kenya$pop_2020 / max_pop)) * 100,
                            ifelse(shape_kenya$pop_density_km2 > 0 & shape_kenya$pop_density_km2 <= 250 & shape_kenya$pop_2020 > 0 & shape_kenya$pop_2020 < 5000, (0.1 * (shape_kenya$pop_density_km2 / max_density) + 0.9 * (shape_kenya$pop_2020 / max_pop)) * 100, (shape_kenya$pop_density_km2 / max_density) * 7 + (shape_kenya$pop_2020 / max_pop) * 3
                                        )
                                    )
                                )

```


```{r}
##Same weights appeoach

# Set the maximum population and population density in the data frame
max_pop <- max(shape_kenya$pop_2020)
max_density <- max(shape_kenya$pop_density_km2)


# Use ifelse statements to calculate the urbanization rate for each county
shape_kenya$urbanization <- ifelse(shape_kenya$pop_density_km2 > 1500 & shape_kenya$pop_2020 >= 50000,
                                    (0.5 * (shape_kenya$pop_density_km2 / max_density + shape_kenya$pop_2020 / max_pop)) * 100,
                                      
                                    ifelse(shape_kenya$pop_density_km2 > 250 & shape_kenya$pop_2020 >= 5000,
                                            (0.5 * (shape_kenya$pop_density_km2 / max_density + shape_kenya$pop_2020 / max_pop)) * 100,
                                        
                                        ifelse(shape_kenya$pop_density_km2 > 0 & shape_kenya$pop_density_km2 <= 250 & shape_kenya$pop_2020 > 0 & shape_kenya$pop_2020 < 5000,
                                                (0.5 * (shape_kenya$pop_density_km2 / max_density + shape_kenya$pop_2020 / max_pop)) * 100,
                                            
                                                (0.7 * (shape_kenya$pop_density_km2 / max_density) + 0.3 * (shape_kenya$pop_2020 / max_pop)) * 100
                                        )
                                    )
                                )

```


```{r}
# Calculate the urbanization rate for each county
#shape_kenya$urbanization3 <- ((0.5 * (log10(shape_kenya$pop_density_km2) / log10(max_density))) + (0.5 * (log10(shape_kenya$pop_2020) / log10(max_pop))))


#shape_kenya$urbanization3 <- shape_kenya$urbanization3 * 100
```


```{r}
# Calculate the urbanization rate for each county
shape_kenya$urbanization2 <- ((0.5 * (log10(shape_kenya$pop_density_km2) / log10(max_density))) + (0.5 * (log10(shape_kenya$pop_2020) / log10(max_pop))))

# Rescale the urbanization values from 0 to 100%
min_urbanization <- min(shape_kenya$urbanization2, na.rm = TRUE)
max_urbanization <- max(shape_kenya$urbanization2, na.rm = TRUE)
shape_kenya$urbanization2 <- ((shape_kenya$urbanization2 - min_urbanization) / (max_urbanization - min_urbanization)) * 100

# Set the urbanization rate of the most rural county to 0%
shape_kenya$urbanization2[which.min(shape_kenya$urbanization2)] <- 0


```

```{r}
#Calculate percentage rural(1-%urban)

shape_kenya$rural <- 100 - shape_kenya$urbanization2

shape_kenya %>% 
    st_write("urbanization.csv")

```

```{r}

shape_kenya2$avg_error <- sqrt(((shape_kenya2$avg_spend - shape_kenya2$avg_spend_per_person)^2)/2)



```





```{r}
# Set plot size and margins
par(mar = c(4, 4, 2, 2), mgp = c(2, 0.7, 0))



# Plot the data
plot(log10(shape_kenya$pop_2020), log10(shape_kenya$pop_density_km2), 
     xlab = "Population (log scale)", ylab = "Population density (log scale)",
     pch = 20, cex = 0.8, col = ifelse(shape_kenya$urbanization2 >= 50, "red", "blue"),
     main = "Urbanization Rates by County in Kenya")

# Add county names as text labels
text(log10(shape_kenya$pop_2020), log10(shape_kenya$pop_density_km2), 
     labels = shape_kenya$NAME_1, cex = 0.6, pos = 4)

# Add a diagonal dashed line to separate blue and red points
abline(a = 0, b = 1, lty = 2)

# Add a legend
legend("topleft", legend = c("Urbanization rate >= 50%", "Urbanization rate < 50%"),
       col = c("red", "blue"), pch = 20, cex = 0.8, bty = "n")




```

```{r}
# Average spend - county vs urbanization method

ggplot(shape_kenya2, aes(x = avg_spend, y = avg_spend_per_person)) +
  geom_point(size = 3) +
  scale_x_log10(name = "Average Spending (Urbanization)") +
  scale_y_log10(name = "Average Spending (County)") +
  theme_classic() +
  geom_text(aes(label = county.y), hjust = 1.2, vjust = 0.5, size = 3)+
  labs(title = "Comparison of Average Spending from County and Urbanization Approaches") 
```


```{r}
ggplot(shape_kenya2, aes(x = avg_spend, y = avg_spend_per_person)) +
  geom_point(size = 3) +
  scale_x_log10(name = "Average Spending (Urbanization)") +
  scale_y_log10(name = "Average Spending (County)") +
  theme_classic() +
  geom_text(aes(label = county.y), hjust = 1.2, vjust = 0.5, size = 3) +
  labs(title = "Comparison of Average Spending from County and Urbanization Approaches") +
  geom_errorbar(aes(x = avg_spend, y = avg_spend_per_person,
                    ymin = avg_spend_per_person - shape_kenya2$avg_error,
                    ymax = avg_spend_per_person + shape_kenya2$avg_error), width = 0)


```

## Greater Nairobi plotting

```{r}
## Read shape file


shape3 <- read_sf(here::here("ken_shape/gadm41_KEN_3.shp"))
shape1 <- read_sf(here::here("ken_shape/gadm41_KEN_1.shp"))


```



```{r}
# Filter the ADM2 boundary data to only show Nairobi and its surroundings
nairobi_adm2 <- shape1[shape1$NAME_1 == "Nairobi" |
                            shape1$NAME_1 == "Kiambu" |
                            shape1$NAME_1 == "Kajiado" |
                            shape1$NAME_1 == "Machakos",]


# Filter the ADM3 boundary data to only show Nairobi and its surroundings
nairobi_adm3 <- shape3[shape3$NAME_3 == "Kitengela" |
                            shape3$NAME_3 == "Ngong" |
                            shape3$NAME_3 == "Ongata Rongai" |
                            shape3$NAME_3 == "Githunguri" |
                            shape3$NAME_3 == "Juja" |
                            shape3$NAME_3 == "Murera" |
                            shape3$NAME_3 == "Theta" |
                            shape3$NAME_3 == "Witeithie" |
                            shape3$NAME_3 == "Kalimoni" |
                            shape3$NAME_3 == "Ndumberi" |
                            shape3$NAME_3 == "Riabai" |
                            shape3$NAME_3 == "Ting'Ang'A"|
                            shape3$NAME_3 == "Karai"|
                            shape3$NAME_3 == "Kikuyu"|
                            shape3$NAME_3 == "Kinoo"|
                            shape3$NAME_3 == "Nachu"|
                            shape3$NAME_3 == "Sigona"|
                            shape3$NAME_3 == "Bibirioni" |
                            shape3$NAME_3 == "Limuru Central" |
                            shape3$NAME_3 == "Limuru East" |
                            shape3$NAME_3 == "Ndeiya"|
                            shape3$NAME_3 == "Ngecha Tigoni"|
                            shape3$NAME_3 == "Biashara"|
                            shape3$NAME_3 == "Gitothua"|
                            shape3$NAME_3 == "Kiuu"|
                            shape3$NAME_3 == "Gatuanyaga"|
                            shape3$NAME_3 == "Hospital"|
                            shape3$NAME_3 == "Kamenu"|
                            shape3$NAME_3 == "Ngoliba"|
                            shape3$NAME_3 == "Kalama"|
                            shape3$NAME_3 == "Kola"|
                            shape3$NAME_3 == "Machakos Central"|
                            shape3$NAME_3 == "Mua"|
                            shape3$NAME_3 == "Mumbuni North"|
                            shape3$NAME_3 == "Mutituni"|
                            shape3$NAME_3 == "Muvuti/Kiima-Kimwe"|
                            shape3$NAME_3 == "Township",]
```


```{r}
# Plot the ADM2 boundary for Nairobi and its surroundings

tm_shape(nairobi_adm2) +
  tm_polygons() +
  tm_text("NAME_1", size = 0.5, col = "black") +
  tm_shape(nairobi_adm3) +
  tm_polygons(col = "red", alpha = 0.4) +
  tm_layout(legend.position = c("left", "bottom"), legend.bg.color = "white") +
  tm_basemap(server = "OpenStreetMap") 
```



```{r}
library(leaflet)


# Set the center and zoom level for the map view
center <- c(-1.28, 36.82)
zoom <- 10

# Create a custom marker icon
icon <- makeIcon(
  iconUrl = "https://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 38, iconHeight = 95,
  iconAnchorX = 22, iconAnchorY = 94,
  popupAnchorX = -3, popupAnchorY = -76
)

# Create a leaflet map with the Kenya ADM1 boundary and the Nairobi ADM2 and ADM3 boundaries
leaflet() %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addPolygons(data = shape1, fillOpacity = 0, color = "black", weight = 2) %>%
  addPolygons(data = nairobi_adm2, fillOpacity = 0.5, color = "blue") %>%
  addPolygons(data = nairobi_adm3, fillOpacity = 0.2, color = "red") %>%
  addMarkers(lng = center[2], lat = center[1], icon = icon) %>%
  setView(lng = center[2], lat = center[1], zoom = zoom)



```


## All city spending

```{r}

cities <- "G:\\Shared drives\\DATA_WDL\\wdp_city_spending\\wdpro_combination"

all_city <- read_rds(paste0(cities,"\\city_distribution.rds"))
```



```{r}
city <- all_city %>%
    filter(ccode %in% c("NGA","ZAF", "KEN")) %>% 
    select("year","ccode","pop","spending_data_datt", "name")


#unnest the list column

city_df <- unnest(city, cols = spending_data_datt)



city_df %>% 
    write_csv("city_spending_rev_2.csv")


```


```{r}

result <- city_df %>%
  filter(year %in% c(2022, 2030)) %>%
  group_by(ccode, name, year) %>%
  mutate(spending_threshold_group = ifelse(spending_threshold >= 80, "over 80",
                                           ifelse(spending_threshold >= 40, "over 40",
                                                  ifelse(spending_threshold >= 12, "over 12", "below 12")))) %>% 
    group_by(ccode, name, year, spending_threshold_group) %>% 
    summarise(headcount_sum = sum(headcount))
 



    
    
    
```


```{r}

resultrev <- result %>%
  filter(year %in% c(2022, 2030)) %>%
  group_by(ccode, name, year) %>%
  mutate(headcount_sum2 = case_when(
    spending_threshold_group == "over 12" ~ sum(headcount_sum[spending_threshold_group %in% c("over 12", "over 40", "over 80")]),
    spending_threshold_group == "over 40" ~ sum(headcount_sum[spending_threshold_group %in% c("over 40", "over 80")]),
    TRUE ~ headcount_sum
  )) %>%
  ungroup() %>%
  select(ccode, name, year, spending_threshold_group, headcount_sum2)



resultrev %>% 
    write_csv("final_city_spending.csv")
```



## Plot bar plots to compare old vs new method($12+ consumer class)


```{r}

library(readxl)
ken_nig_sa <- read_xlsx("ken_nig_sa.xlsx")

```


```{r}


# Calculate mean square percentage error for each city in Nigeria
df_nig <- ken_nig_sa %>% 
    filter(Country == "Nigeria") %>% 
    mutate(mspe = ((new_method - old_method) / old_method) ^ 2 * 100)

# Create bar plot
plot_nig <- ggplot(df_nig, aes(x = reorder(City, -old_method), y = old_method, fill = "Old Method")) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_bar(aes(y = new_method, fill = "New Method"), stat = "identity", position = "dodge") +
  labs(x = "City", y = "$12+ Consumer class", title = "Comparison of Old vs New Method for $12+ consumer class in Nigeria",
       fill = "") +
  theme_minimal() +
  coord_flip() +
  theme(axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10),
        plot.title = element_text(size = 12))

# Add mean square percentage error
plot_nig + geom_text(aes(label = paste0(round(mspe, 2), "%")), 
                 position = position_dodge(width = 0.9), vjust = -0.5, size = 2)


    
```

```{r}
# Calculate mean square percentage error for each city in Kenya
df_ken <- ken_nig_sa %>% 
    filter(Country == "Kenya") %>% 
    mutate(mspe = ((new_method - old_method) / old_method) ^ 2 * 100)

# Create bar plot
plot_ken <- ggplot(df_ken, aes(x = reorder(City, -old_method), y = old_method, fill = "Old Method")) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_bar(aes(y = new_method, fill = "New Method"), stat = "identity", position = "dodge") +
  labs(x = "City", y = "$12+ Consumer class", title = "Comparison of Old vs New Method for $12+ consumer class in Kenya",
       fill = "") +
  theme_minimal() +
  coord_flip() +
  theme(axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10),
        plot.title = element_text(size = 12))

# Add mean square percentage error
plot_ken + geom_text(aes(label = paste0(round(mspe, 2), "%")), 
                 position = position_dodge(width = 0.9), vjust = -0.5, size = 2)
```

```{r}
# Calculate mean square percentage error for each city
df_sa <- ken_nig_sa %>% 
    filter(Country == "South Africa") %>% 
    mutate(mspe = ((new_method - old_method) / old_method) ^ 2 * 100)

# Create bar plot
plot_sa <- ggplot(df_sa, aes(x = reorder(City, -old_method), y = old_method, fill = "Old Method")) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_bar(aes(y = new_method, fill = "New Method"), stat = "identity", position = "dodge") +
  labs(x = "City", y = "$12+ Consumer class", title = "Comparison of Old vs New Method for $12+ consumer class in S.Africa",
       fill = "") +
  theme_minimal() +
  coord_flip() +
  theme(axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10),
        plot.title = element_text(size = 11))

# Add mean square percentage error
plot_sa + geom_text(aes(label = paste0(round(mspe, 2), "%")), 
                 position = position_dodge(width = 0.9), vjust = -0.5, size = 2)
```

```{r}

# Create scatter plot with line of equality
plot <- ggplot(df_nig, aes(x = old_method, y = new_method, label = City)) + 
  geom_point() +
  scale_x_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  scale_y_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  labs(x = "Old Method (in thousands)", y = "New Method (in thousands)", 
       title = "Old vs New Method for $12 + in Nigeria") +
  theme_minimal()

# Add line of equality
plot + geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = City), size = 2, hjust = -0.1, vjust = 0.5) +
  theme(axis.title.x = element_text(size = 10), 
             axis.title.y = element_text(size = 10),
             plot.title = element_text(size = 11))




```

```{r}
# Create scatter plot with line of best fit
plot1 <- ggplot(df_ken, aes(x = old_method, y = new_method, label = City)) + 
  geom_point() +
  scale_x_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  scale_y_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  labs(x = "Old Method (in thousands)", y = "New Method (in thousands)", 
       title = "Old vs New Method for $12 + in Kenya") +
  theme_minimal()

# Modify axis labels
plot1 + geom_abline(intercept = 0, slope = 1, color = "red")+
    geom_text(aes(label = City), size = 2, hjust = -0.1, vjust = 0.5) +
    theme(axis.title.x = element_text(size = 10), 
             axis.title.y = element_text(size = 10),
             plot.title = element_text(size = 11))
```

```{r}
# Create scatter plot with line of best fit
plot2 <- ggplot(df_sa, aes(x = old_method, y = new_method, label = City)) + 
  geom_point() +
  scale_x_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  scale_y_continuous(labels = scales::unit_format(unit = "k", scale = 1e-3))+
  labs(x = "Old Method (in thousands)", y = "New Method (in thousands)", 
       title = "Old vs New Method for $12 + in S.Africa") +
  theme_minimal()

# Modify axis labels
plot2 + geom_abline(intercept = 0, slope = 1, color = "red") +
    geom_text(aes(label = City), size = 2, hjust = -0.1, vjust = 0.5) +
    theme(axis.title.x = element_text(size = 10), 
             axis.title.y = element_text(size = 10),
             plot.title = element_text(size = 11))
```

