---
title: "drc_plot"
output: html_document
date: "2023-06-23"
---

```{r}
#Load libraries

library(tidyverse)
library(here)
library(viridis)
library(sf)
library(tmap)
library(ggpp)
library(raster)
library(rasterVis)
library(readxl)
library(xml2)
library("RColorBrewer")
library(foreign)
library(haven)
library(Hmisc)
library(fuzzyjoin)
```


```{r}
library(tmap)
library(leaflet)

# Create a data frame with the city information
cities <- data.frame(
  City = c("Bukavu", "Bunia", "Goma", "Kabinda", "Kananga", "Kikwit", "Kinshasa", "Kisangani",
           "Kolwezi", "Likasi", "Lubumbashi", "Matadi", "Mbandaka", "Mbuji-Mayi", "Tshikapa", "Uvira"),
  Population = c(1252857, 811978, 745591, 570294, 1672811, 572100, 16404060, 1432538,
                 530897, 632730, 2828109, 435342, 498182, 2905109, 1079228, 692407),
  lat = c(-2.5083, 1.5667, -1.6792, -6.1379, -5.8962, -5.041, -4.3276, 0.5167, -10.7148,
          -10.9814, -11.6609, -5.8177, 0.0487, -6.15, -6.4162, -3.3953),
  lon = c(28.8608, 30.25, 29.2228, 24.4818, 22.4166, 18.8162, 15.3136, 25.2, 25.4667,
          26.7333, 27.4794, 13.4717, 18.2603, 23.6, 20.8, 29.1378)
)

# Create a leaflet map
map <- leaflet() %>%
  setView(lng = 25, lat = 0, zoom = 5)  # Set the initial view of the map

# Add the outline of DRC
map <- map %>% addTiles() %>%
  addPolygons(
    lng = c(12.19, 30.8489, 30.8489, 12.19, 12.19),
    lat = c(-13.455, -13.455, 5.377, 5.377, -13.455),
    fillColor = "transparent",
    color = "blue"
  )

# Calculate the size of dots proportional to the city population
dot_size <- sqrt(cities$Population / max(cities$Population)) * 30

# Add the cities as dots on the map
map <- map %>% addCircleMarkers(
  lng = cities$lon,
  lat = cities$lat,
  radius = dot_size,
  color = "red",
  fillOpacity = 0.8
)

# Display the map
map

```


```{r}
library(leaflet)

# Create a data frame with the city information
cities <- data.frame(
  City = c("Bukavu", "Bunia", "Goma", "Kabinda", "Kananga", "Kikwit", "Kinshasa", "Kisangani",
           "Kolwezi", "Likasi", "Lubumbashi", "Matadi", "Mbandaka", "Mbuji-Mayi", "Tshikapa", "Uvira"),
  Population = c(1252857, 811978, 745591, 570294, 1672811, 572100, 16404060, 1432538,
                 530897, 632730, 2828109, 435342, 498182, 2905109, 1079228, 692407),
  lat = c(-2.5083, 1.5667, -1.6792, -6.1379, -5.8962, -5.041, -4.3276, 0.5167, -10.7148,
          -10.9814, -11.6609, -5.8177, 0.0487, -6.15, -6.4162, -3.3953),
  lon = c(28.8608, 30.25, 29.2228, 24.4818, 22.4166, 18.8162, 15.3136, 25.2, 25.4667,
          26.7333, 27.4794, 13.4717, 18.2603, 23.6, 20.8, 29.1378)
)

# Create a leaflet map centered on the Democratic Republic of the Congo (DRC)
map <- leaflet() %>%
  setView(lng = 23.6, lat = -2.5, zoom = 6)

# Add tiles to the map
map <- map %>%
  addTiles("Stamen.TonerLite") %>%
  addProviderTiles("Stamen.TonerLite", options = providerTileOptions(noWrap = TRUE))

# Calculate the size of dots proportional to the city population
dot_size <- sqrt(cities$Population / max(cities$Population)) * 20

# Add city dots with popups to the map
for (i in 1:nrow(cities)) {
  city <- cities[i, ]
  map <- map %>%
    addCircleMarkers(
      lng = city$lon, lat = city$lat,
      radius = dot_size[i],
      color = "red",
      fillOpacity = 0.8,
      label = paste0(city$City),
      labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE, direction = "bottom")
    )
}

# Save the map as an HTML file
saveWidget(map, "drc_cities_map.html", selfcontained = TRUE)

# Display the map
map





```





```{r}
library(leaflet)
library(webshot)

# Create a data frame with the city information
cities <- data.frame(
  City = c("Bukavu", "Bunia", "Goma", "Kabinda", "Kananga", "Kikwit", "Kinshasa", "Kisangani",
           "Kolwezi", "Likasi", "Lubumbashi", "Matadi", "Mbandaka", "Mbuji-Mayi", "Tshikapa", "Uvira"),
  Population = c(1252857, 811978, 745591, 570294, 1672811, 572100, 16404060, 1432538,
                 530897, 632730, 2828109, 435342, 498182, 2905109, 1079228, 692407),
  lat = c(-2.5083, 1.5667, -1.6792, -6.1379, -5.8962, -5.041, -4.3276, 0.5167, -10.7148,
          -10.9814, -11.6609, -5.8177, 0.0487, -6.15, -6.4162, -3.3953),
  lon = c(28.8608, 30.25, 29.2228, 24.4818, 22.4166, 18.8162, 15.3136, 25.2, 25.4667,
          26.7333, 27.4794, 13.4717, 18.2603, 23.6, 20.8, 29.1378)
)

# Create a leaflet map centered on the Democratic Republic of the Congo (DRC)
map <- leaflet() %>%
  setView(lng = 23.6, lat = -2.5, zoom = 6)

# Add tiles to the map
map <- map %>%
  addTiles("Stamen.TonerLite") %>%
  addProviderTiles("Stamen.TonerLite", options = providerTileOptions(noWrap = TRUE))

# Calculate the size of dots proportional to the city population
dot_size <- sqrt(cities$Population / max(cities$Population)) * 30

# Add city dots with popups to the map
for (i in 1:nrow(cities)) {
  city <- cities[i, ]
  map <- map %>%
    addCircleMarkers(
      lng = city$lon, lat = city$lat,
      radius = dot_size[i],
      color = "red",
      fillOpacity = 0.8,
      label = paste0(city$City, "Population: ", format(city$Population, big.mark = ",")),
      labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE, direction = "center")
    )
}

# Save the map as a PNG file

webshot::webshot("/Users/lindakarani/Documents/gitrepo/city_level_modelling/drc_cities_map.html","drc5.png")

# Display the map
map


```


```{r}
library(leaflet)
library(leafem)
library(htmltools)

# Create a data frame with the city information
cities <- data.frame(
  City = c("Bukavu", "Bunia", "Goma", "Kabinda", "Kananga", "Kikwit", "Kinshasa", "Kisangani",
           "Kolwezi", "Likasi", "Lubumbashi", "Matadi", "Mbandaka", "Mbuji-Mayi", "Tshikapa", "Uvira"),
  Population = c(1252857, 811978, 745591, 570294, 1672811, 572100, 16404060, 1432538,
                 530897, 632730, 2828109, 435342, 498182, 2905109, 1079228, 692407),
  lat = c(-2.5083, 1.5667, -1.6792, -6.1379, -5.8962, -5.041, -4.3276, 0.5167, -10.7148,
          -10.9814, -11.6609, -5.8177, 0.0487, -6.15, -6.4162, -3.3953),
  lon = c(28.8608, 30.25, 29.2228, 24.4818, 22.4166, 18.8162, 15.3136, 25.2, 25.4667,
          26.7333, 27.4794, 13.4717, 18.2603, 23.6, 20.8, 29.1378)
)

# Create a leaflet map centered on the Democratic Republic of the Congo (DRC)
map <- leaflet() %>%
  setView(lng = 23.6, lat = -2.5, zoom = 6)

# Add tiles to the map
map <- map %>%
  addTiles("Stamen.TonerLite") %>%
  addProviderTiles("Stamen.TonerLite", options = providerTileOptions(noWrap = TRUE))

# Calculate the size of dots proportional to the city population
dot_size <- sqrt(cities$Population / max(cities$Population)) * 20

# Add city dots with labels to the map
for (i in 1:nrow(cities)) {
  city <- cities[i, ]
  label_text <- paste("City:", city$City, "<br>", "Population:", format(city$Population, big.mark = ","))
  map <- map %>%
    addCircleMarkers(
      lng = city$lon, lat = city$lat,
      radius = dot_size[i],
      color = "red",
      fillOpacity = 0.8,
      label = lapply(label_text, HTML),
      labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE, direction = "center")
    )
}

# Capture the map as an HTML widget
map_widget <- mapshot(map, file = "drc.html")

# Save a screenshot of the map widget
saveWidget(map_widget, file = "drc.png", selfcontained = TRUE)



```



