---
title: "kenya survey spending"
output: html_document
date: "2023-06-20"
---

```{r}
#Load libraries

library(tidyverse)
library(here)
library(viridis)
library(sf)
library(tmap)
library(ggpp)
library(raster)
library(rasterVis)
library(readxl)
library(xml2)
library("RColorBrewer")
library(foreign)
library(haven)
library(Hmisc)
library(fuzzyjoin)
```

## Creating spending buckets using Kenyan survey data to compare to city approaches
```{r}


##Read Kenya consumption survey data

ken_cons <- read_dta("ken_consumption//Consumption_aggregate.dta")

##Use string to get column descriptions
str(ken_cons)

#Convert column county and resid to factor columns
ken_cons$county <- as_factor(ken_cons$county)
ken_cons$resid <- as_factor(ken_cons$resid)
ken_cons$eatype <- as_factor(ken_cons$eatype)

#Get the total consumption

ken_cons <- ken_cons %>%
    rename(tot_cons = padqexp)

#Read ppp conversion factors

ppp_2017 <- read_rds("01_010_conversion_factors.rds")

#Filter for only Kenya

ppp_2017_ken <- ppp_2017 %>% 
    filter(ccode == "KEN")

# Get per person spending by dividing by the household size

ken_cons2 <- ken_cons %>% 
    mutate(individual_spend = (tot_cons * ctry_adq) /hhsize/30)

##Divide by conversion factor for 2016 to convert local currency to 2017ppp
ken_cons_ppp <- ken_cons2 %>% 
    mutate(tot_cons_ppp = (individual_spend/38.344658))



```




```{r}
##Create spending groups that Match WDPro

# Define spending buckets
buckets <- c(0.00, 1.00, 2.00, 2.15, 3.00, 3.65, 4.00,5.00,6.00,6.85,7.00,8.00,9.00,10.00,11.00,12.00,13.00,14.00,15.00,16.00,17.00,18.00,19.00,20.00,21.00,22.00,23.00,24.00,25.00,26.00,27.00,28.00,29.00,30.00,31.00,32.00,33.00,34.00,35.00,36.00,37.00,38.00,39.00,40.00,41.00,42.00,43.00,44.00,45.00,46.00,47.00,48.00,49.00,50.00,51.00,52.00,53.00,54.00,55.00,56.00,57.00,58.00,59.00,60.00,61.00,62.00,63.00,64.00,65.00,66.00,67.00,68.00,69.00,70.00,71.00,72.00,73.00,74.00,75.00,76.00,77.00,78.00,79.00,80.00,81.00,82.00,83.00,84.00,85.00,86.00,87.00,88.00,89.00,90.00,91.00,92.00,93.00,94.00,95.00,96.00,97.00,98.00,99.00,100.00,101.00,102.00,103.00,104.00,105.00,106.00,107.00,108.00,109.00,110.00,111.00,112.00,113.00,114.00,115.00,116.00,117.00,118.00,119.00,120.00,121.00,122.00,123.00,124.00,125.00,126.00,127.00,128.00,129.00,130.00,131.00,132.00, 133.00,134.00,135.00,136.00,137.00,138.00,139.00,140.00,141.00,142.00,143.00,144.00,145.00,146.00,147.00,148.00,149.00,150.00, 151.00,152.00,153.00,154.00,155.00,156.00,157.00,158.00,159.00,160.00,3000.00)  

# Create empty result dataframe
df <- data.frame(
  inc_lwr = numeric(0),
  inc_upr = numeric(0),
  total_weighted_pop = numeric(0),
  total_spending = numeric(0),
  stringsAsFactors = FALSE
)

# Iterate over the spending buckets
for (i in 1:(length(buckets) - 1)) {
  lower_limit <- buckets[i]
  upper_limit <- buckets[i+1]
  
  # Filter the dataframe for the current spending bucket
  df2 <- ken_cons_ppp[ken_cons_ppp$tot_cons_ppp >= lower_limit & ken_cons_ppp$tot_cons_ppp < upper_limit, ]
  
  # Calculate total weighted population and total spending for the current bucket
  total_weighted_pop <- sum(df2$weight_pop)
  total_spending <- sum(df2$tot_cons_ppp * df2$weight_pop)
  
  # Add the results to the result dataframe
  df <- rbind(df, data.frame(inc_lwr = lower_limit, inc_hgr = upper_limit, total_weighted_pop, total_spending))
}



test <- df %>% 
    filter(inc_hgr >12 & inc_hgr < 40)
```




```{r}
## Get consumer class distribution from survey for 2016 - slide 16

survey_df <- df %>%
  mutate(spending_threshold_group = ifelse(inc_hgr < 12,  "below 12",
                                    ifelse(inc_hgr > 12 & inc_hgr < 40, "over 12",
                                    ifelse(inc_hgr > 40 & inc_hgr < 80  , "over 40",
                                    ifelse(inc_hgr > 80 & inc_hgr < 120, "over 80", "over 120"))))) %>% 
  group_by(spending_threshold_group) %>% 
  summarise(headcount_sum = round(sum(total_weighted_pop)),
            tot_spend = round(sum(total_spending)))
```



```{r}
##Totals from grouped survey data (by spending group)

kensurvey <- survey_df %>% 
    summarise(pop = sum(headcount_sum),
              spend = sum(tot_spend))

##Check that totals match raw survey data
survey_tot <- ken_cons_ppp %>% 
  summarise(pop = sum(weight_pop),
            spend = sum(tot_cons_ppp * weight_pop))
```

```{r}
# copy data
ken_1 <- ken_cons

# compute daily spending per capita
# Daily spending per capita
# = "Monthly per adult equivalent total consumption expenditure (deflated)"
# * "Sum total of adult equivalent scales (country-specific)"
# / "Total Persons In Household"
# / 30
ken_1$spend_pc <- ken_1$padqexp * ken_1$ctry_adq / ken_1$hhsize / 30

# turn spending per capita into 2017 ppp
ken_1$spend_pc <- ken_1$spend_pc /
  ppp_2017$hhe_2017ppp_to_current_LCU[ppp_2017$ccode=="KEN" & ppp_2017$year==2016]

# add wdp spending levels
ken_1$spend_group <- cut(ken_1$spend_pc, breaks = c(0, 12, 40, 80, 120, Inf), right = FALSE)

# sum up weights and spending by spending levels
ken_1 <- ken_1 %>%
  group_by(spend_group) %>%
  summarise(hc = round(sum(weight_pop)),
            exp = round(sum(spend_pc*weight_pop))) %>%
  ungroup()

# add totals
ken_2 <- data.frame(spend_group = "total", hc = sum(ken_1$hc), exp = sum(ken_1$exp))
ken_1 <- rbind(ken_1, ken_2)

```

