---
title: "subnational_cons_spending"
output: html_document
date: "2023-03-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load libraries

library(tidyverse)
library(here)
library(viridis)
library(sf)
library(ggpp)
library(raster)
library(rasterVis)
library(readxl)
library(xml2)
library("RColorBrewer")
```


```{r}

path <- "G:\\Shared drives\\DATA_WDL\\Mpro_2.0\\01_Data\\R_2022_12_29\\2023_01_23_2017ppp\\01_inputs\\population\\World pop\\Ethiopia"

path_uga <- "G:\\Shared drives\\DATA_WDL\\Mpro_2.0\\01_Data\\R_2022_12_29\\2023_01_23_2017ppp\\01_inputs\\population\\World pop\\Uganda"


#Load tz population data and shape file


tz_pop <- raster("tza_ppp_2020_UNadj_constrained.tif")
shape_tz <- read_sf(here::here("tz_shape/tza_admbnda_adm3_20181019.shp")) 

#Load Ethiopia population data and shape file

eth_pop <-  raster(paste0(path, "\\eth_ppp_2020_UNadj_constrained.tif"))
shape_eth <- read_sf(here::here("eth_shape/Eth_Woreda_2013.shp")) 

#Load Kampala population data and shape file

uga_pop <-  raster(paste0(path_uga, "\\uga_ppp_2020_UNadj_constrained.tif"))
shape_uga <- read_sf(here::here("uga_shape/uga_admbnda_adm3_ubos_20200824.shp")) 


```



## Greater Dar-es-salaam modelling
```{r}
##Extract values from raster file using shape file


library(exactextractr)

shape_tz$pop_2020 <- exact_extract(tz_pop, shape_tz, 'sum')

shape_tz %>% 
    st_write("tz_pop_2020.csv")

```


```{r}
#Total Dares salaam population 2020

shape_tz %>% 
    filter(ADM1_EN == "Dar-es-salaam") %>% 
    summarise(tot = sum(pop_2020))

```


```{r}
#scale population to 2022 and 2030

shape_tz <- shape_tz %>% 
    mutate(pop_2022 = pop_2020* 1.020971,
           pop_2030 = pop_2020* 1.4901893)
```

```{r}
#Get consumer class breakdown

shape_tz <- shape_tz %>% 
    mutate(cons_class12 = pop_2022*0.155983045,
           cons_class40 = pop_2022*0.012511521,
           cons_class80 = pop_2022*0.003190343,
           cons_class12_2030 = pop_2030*0.25865929,
           cons_class40_2030 = pop_2030*0.020396116,
           cons_class80_2030 = pop_2030*0.005052277)
    

```

```{r}
#Get consumer class breakdown for 15 + year old

shape_tz <- shape_tz %>% 
     mutate(Females_2022_12USD = cons_class12*0.360033924,
           Males_2022_12USD = cons_class12*0.384913863,
           Females_2022_40USD = cons_class40*0.360026466,
           Males_2022_40USD = cons_class40*0.384916272,
           Females_2022_80USD = cons_class80*0.360052913,
           Males_2022_80USD = cons_class80*0.384881517,
           Females_2030_12USD = cons_class12_2030*0.368186253,
           Males_2030_12USD = cons_class12_2030*0.387125694,
           Females_2030_40USD = cons_class40_2030*0.368173541,
           Males_2030_40USD = cons_class40_2030*0.387140555,
           Females_2030_80USD = cons_class80_2030*0.368200755,
           Males_2030_80USD = cons_class80_2030*0.387146673)

```

```{r}
shape_tz %>% 
    st_write("fin_con_tz.csv")
```


## Greater Addis consumer spending
```{r}
##Extract values from raster file using shape file


library(exactextractr)

shape_eth$pop_2020 <- exact_extract(eth_pop, shape_eth, 'sum')

shape_eth <- shape_eth %>% 
    st_write("eth_pop_2020.csv")

```


```{r}
#Total Addis Ababa population 2020

shape_eth %>% 
    filter(REGIONNAME == "Addis Ababa") %>% 
    summarise(tot = sum(pop_2020))

```


```{r}
#scale population to 2022 and 2030

shape_eth <- shape_eth %>% 
    mutate(pop_2022 = pop_2020* 1.326136514,
           pop_2030 = pop_2020* 1.864508179)
```



```{r}
#Get consumer class breakdown

shape_eth <- shape_eth %>% 
    mutate(cons_class12 = pop_2022*0.296895518,
           cons_class40 = pop_2022*0.01448376,
           cons_class80 = pop_2022*0.013873240,
           cons_class12_2030 = pop_2030*0.606674807,
           cons_class40_2030 = pop_2030*0.050651533,
           cons_class80_2030 = pop_2030*0.011372521)
    

```


```{r}
#Get consumer class breakdown for 15 + year old

shape_eth <- shape_eth %>% 
     mutate(Females_2022_12USD = cons_class12*0.332678169,
           Males_2022_12USD = cons_class12*0.376695282,
           Females_2022_40USD = cons_class40*0.332683254,
           Males_2022_40USD = cons_class40*0.376700745,
           Females_2022_80USD = cons_class80*0.3326833,
           Males_2022_80USD = cons_class80*0.376700745,
           Females_2030_12USD = cons_class12_2030*0.368448132,
           Males_2030_12USD = cons_class12_2030*0.387125694,
           Females_2030_40USD = cons_class40_2030*0.347826907,
           Males_2030_40USD = cons_class40_2030*0.368457839,
           Females_2030_80USD = cons_class80_2030*0.347826907,
           Males_2030_80USD = cons_class80_2030*0.368457839)

```



```{r}

shape_eth %>% 
    st_write("fin_con_eth.csv")

```


## Greater Kampala consumer spending
```{r}
##Extract values from raster file using shape file


library(exactextractr)

shape_uga$pop_2020 <- exact_extract(uga_pop, shape_uga, 'sum')

shape_uga <- shape_uga %>% 
    st_write("uga_pop_2020.csv")

```


```{r}
#Total Kampala population 2020

shape_uga %>% 
    filter(ADM2_EN == "Kampala") %>% 
    summarise(tot = sum(pop_2020))

```


```{r}
#scale population to 2022 and 2030

shape_uga <- shape_uga %>% 
    mutate(pop_2022 = pop_2020* 1.975556724,
           pop_2030 = pop_2020*  2.97582534)
```



```{r}
#Get consumer class breakdown

shape_uga <- shape_uga %>% 
    mutate(cons_class12 = pop_2022*0.204582718,
           cons_class40 = pop_2022*0.014516643,
           cons_class80 = pop_2022*0.00339965,
           cons_class12_2030 = pop_2030*0.367557857,
           cons_class40_2030 = pop_2030*0.026202479,
           cons_class80_2030 = pop_2030*0.00601898)
    

```


```{r}
#Get consumer class breakdown for 15 + year old

shape_uga <- shape_uga %>% 
     mutate(Females_2022_12USD = cons_class12*0.35248987,
           Males_2022_12USD = cons_class12*0.417886807,
           Females_2022_40USD = cons_class40*0.352532214,
           Males_2022_40USD = cons_class40*0.417811449,
           Females_2022_80USD = cons_class80*0.352626564,
           Males_2022_80USD = cons_class80*0.417651899,
           Females_2030_12USD = cons_class12_2030*0.348145372,
           Males_2030_12USD = cons_class12_2030*0.39538472,
           Females_2030_40USD = cons_class40_2030*0.348130275,
           Males_2030_40USD = cons_class40_2030*0.395394744,
           Females_2030_80USD = cons_class80_2030*0.348089774,
           Males_2030_80USD = cons_class80_2030*0.39540101)

```


```{r}

shape_uga %>% 
    st_write("fin_con_uga.csv")

```
## Plot maps for the three cities
```{r}
shape_uga %>% 
    filter(ADM2_EN %in% c("Kampala", "Mpigi", "Wakiso", "Mukono", "Buikwe", "Luwero")) %>% 
  ggplot() + 
  geom_sf(mapping = aes(fill = cons_class12), show.legend = TRUE) +
  geom_sf_text(aes(label = ADM2_EN), size = 2.5) + 
  coord_sf() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        rect = element_blank()) +
  labs(fill = "Total $40+ population in 2022") +
  scale_fill_viridis(option = "plasma", direction = -1) +
  theme(plot.title = element_text(size = 15, face = "bold")) + # adjust plot subtitle size
  ggtitle("$40+ population in 2022") 

ggsave("kampala_consumer class.png", width = 14, height = 12, dpi = 300, bg = "white" )



```



